APP_PORT = 80
APP_ADDRESS = '0.0.0.0'
APP_NAME = 'Тестовое задание'
DEBUG = True
ENV = 'development'
URL_ARTIST = 'https://api.deezer.com/artist/'
URL_GENRE = 'https://api.deezer.com/genre/'
IMAGE_ARTISTS_DIR = '/static/img/artists/'
IMAGE_ALBUMS_DIR = '/static/img/albums/'
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
SECRET_KEY = 'Security below zero'
BOOTSTRAP_SERVE_LOCAL = True
MYSQL_DATABASE_USER = 'root'
MYSQL_DATABASE_PASSWORD = 'root'
MYSQL_DATABASE_DB = 'deezerparsing'
MYSQL_DATABASE_HOST = 'db'
MYSQL_DATABASE_PORT = '3306'
ROWS_PER_PAGE = 5
